<?php

/**
 * ProcessWire Module Fieldtype Select External Option 
 * extend all Selectfieldtypes
 * provide all Inputfields
 * 
 * pulls options (value/ label pairs) from other datatable (also other fields) 
 * access to selected datatable row via Api
 * 
 * 
 * made by kixe (Christoph Thelen) 09.03.15
 * Licensed under GNU/GPL v3
 * v 1.1.1 12.05.15
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2013 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://processwire.com
 *
 *
 *
 */

class FieldtypeSelectExtOption extends FieldtypeMulti {

	public static function getModuleInfo() {
		return array(
			'title' => 'Select External Option',
			'version' => 111,
			'summary' => __('Fieldtype which generates the options for a Select Inputfield from *any* table in the database. Define the source table, columns (to pull value & label) and the preferred Inputfieldtype in field settings.'),
			'author' => 'kixe',
			'href' => 'http://modules.processwire.com/modules/fieldtype-select-ext-option/',
			'license' => 'GNU-GPLv3',
			'hreflicense' => 'http://www.gnu.org/licenses/gpl-3.0.html',
			'icon' => 'database',
			'requires' => 'ProcessWire>=2.5.0'
		);
	}
	
    protected $page;
    	
	/**
	 * Get an associative array of all values of the row depending to the selected single value.
	 *
	 * @param object $field
	 * @param int $value
	 * @return array / empty if column holding the values is not defined
	 *
	 */
	protected function getTableRow(Field $field,$value) {	
		$table = $field->option_table;
		if(!$table) {
			return array();
        }
		$columns = $this->getDatabaseColumns($table);
		$valuecolumn = $field->option_value;
		if(!in_array($valuecolumn,$columns)) {
			return array();
		}
		$table = $this->database->escapeTable($table);
		$value = (int)$value;
		$sql = "SELECT * FROM `$table` WHERE $valuecolumn = '$value'";
		
		$query = $this->database->query($sql);
		if(!$query->rowCount()) return array();
		return $query->fetch(); // single return, unique value
	}

	public function row($name = null, $selector = null) {
		$return = array();
		$n = $name;
		if ($name) $name = ',name='.$name;
		$page = ($selector)?$this->wire('pages')->get($selector):$this->wire('page');
		if ($page instanceof NullPage) return "Page not found. Selector string '$selector' doesn't match.";
		$field = $page->fields->get('type=FieldtypeSelectExtOption'.$name);
		//field does not belong to pages fieldgroup
		if (!$name && !$field) return "Page '$page->name' doesn't contain any field of type 'SelectExtOption'!";
		if (!$field) return "Field '$n' doesn't belong to page '$page->name'.";

		$name = $field->name;
		$value = $page->$name;

		if ($value instanceof WireArray) foreach ($value as $val) {
			$row = $this->getTableRow($field,$val->value);
			$return[] = $row;
		} else {
			$this->getTableRow($field,$value->value);
			$return = $this->getTableRow($field,$value->value);
		}
		return $return;
		
	}

	public function getInputfield(Page $page, Field $field) {
	
		// set property
    	$this->page = $page;
		$v = $this->sleepValue($page,$field,$page->$field);
		// prevent frontend error
		$class = ($field->input_type)?$field->input_type:'InputfieldSelect';

		/**
		 * Hook prevents object to string conversion in Class InputfieldSelect.
		 * 
		 * @return int/ array
		 *
		 */
     	$this->addHookBefore($class.'::render', function($event) {
   		$field = $event->object->name;
   			$extopt = wire('modules')->get('FieldtypeSelectExtOption');
		   	$object = $extopt->page->$field;
			if ($object instanceof SelectExtOption) $event->object->setAttribute('value',$object->value);
			if ($object instanceof WireArray && $object->first() instanceof SelectExtOption) {
				$attrValue = array();
				foreach ($object as $value) $attrValue[] = $value->value;
				$event->object->setAttribute('value',$attrValue);
			}
    	});
    	
		$inputfield = $this->modules->get($class);

		// get the options array
		$options = $this->getExtOptions($field->option_table,$field->option_value,$field->option_label,$this->filter($field),$field->option_order,$field->option_asc);
		$options = ($options)?$options:array(0 => 'no data');

		foreach($options as $optval => $label) {			
			$inputfield->addOption($optval,$label);
		}
		return $inputfield;
	}

	/**
	 * Get an array of all columns in a given table of the database.
	 *
	 * @param string name of the table
	 * @return array
	 *
	 */
	protected function getDatabaseColumns($table) {
		if(!in_array($table,$this->database->getTables())) return null;
		$columns = array();
		$table = $this->database->escapeTable($table);
		$sql = "SHOW COLUMNS FROM $table"; 			
		$query = $this->database->query($sql);
		if(!$query->rowCount()) return null;
		$rows = $query->fetchAll();
		foreach($rows as $row) $columns[] = $row['Field'];
		return $columns; 
		
	}

	/**
	 * Return true if column in a given table of the database is of type (int).
	 *
	 * @param string datatable and column
	 * @return null (if table and/or column doesn't exist)
	 * @return bool (true if int)
	 *
	 */
	protected function isIntColumn($table,$column) {
		$result = array();
		$columns = $this->getDatabaseColumns($table);
		if(!$columns) return null;
		if(!in_array($column,$columns)) return null;
		$table = $this->database->escapeTable($table);
		$column = $this->database->escapeCol($column);
		$sql = "SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '$table' AND COLUMN_NAME = '$column'";
		$query = $this->database->query($sql);
		if(!$query->rowCount()) return null;
		foreach($query->fetchAll() as $type) if(strpos($type[0],'int') !== false) return true;
		return false;
	}

	/**
	 * Get options array from external field or datatable
	 *
	 * @return bool false if table and/or column doesn't exist
	 * @return null if table doesn't contain any data
	 * @return array(value => label)
	 *
	 */
	protected function getExtOptions($table, $value = false, $label = false, $filter= false, $order = false, $dir = false) {

		// check if table exist
		$table = $this->database->escapeTable($table);
		if(!in_array($table,$this->database->getTables())) return false;

		// get columns array
		$columns = $this->getDatabaseColumns($table);

		// we need minimum one inttype column 
		foreach ($columns as $column) {
			if ($this->isIntColumn($table,$column)) $intcolumn = $column; break;
		}
		if (!isset($intcolumn)) return false;

		// check if column isset and exist, default 1st column
		if($label === false) $label = $columns[0];
		else if(!in_array($label,$columns))return false;

		// check if column isset and exist, default 1st column of type int
		if($value === false) $value = $intcolumn;
		else if(!in_array($value,$columns))return false;

		$options = array();
		
		$dir = ((bool)$dir)?'DESC':'ASC';
		$order = ($order)?$order:$label;
		$order = $this->database->escapeCol($order);
		// validate/sanitize filterstring
		$filter = ($filter)?"WHERE $filter":'';
		$query = $this->database->prepare("SELECT * FROM `$table` $filter ORDER BY $order $dir");
		$query->execute();
		if(!$query->rowCount()) return null;
        while($row = $query->fetch(PDO::FETCH_ASSOC)) $options[$row[$value]] = $row[$label];
        return $options;
	}

	protected function filter(Field $field) {
		// all parts set?
		if(!$field->filter_column||!$field->filter_selector||!$field->filter_value) return false;
		// valid operator?
		$operators = array(' LIKE ',' NOT LIKE ');
		if(!$this->database->isOperator($field->filter_selector) && !in_array($field->filter_selector,$operators))  return false;
		// escape column, quote value
		return $this->database->escapeCol($field->filter_column).$field->filter_selector.$this->database->quote($field->filter_value);
	}

	public function getBlankValue(Page $page, Field $field) {
		return (!$field->input_type)?new SelectExtOption():new WireArray();
	}

	public function getSingleValue(Field $field, $value) {
		$new = new SelectExtOption();
		$new->value = ($value !== null)?(int)$value:null;	
		$row = $this->getTableRow($field,$new->value);
		if ($row) {
			$new->label = $field->option_label?$row[$field->option_label]:array_pop($row);
			$new->row = $this->getTableRow($field,$new->value);
			return $new;
		}
		return new SelectExtOption();
	}

	public function sanitizeValue(Page $page, Field $field, $value) {
		if($value instanceof SelectExtOption) return $value;
		if($value instanceof WireArray) return $value;
		if(!$value) return $this->getBlankValue($page,$field);
		if(is_string($value)) return $this->getSingleValue($field,$value);
		$return = new WireArray();
		foreach ($value as $val) $return->add($this->getSingleValue($field,$val));
		return $return;
	}

    public function wakeupValue(Page $page, Field $field, $value) {
		if(!$value) return $this->getBlankValue($page,$field);
		$module = $this->modules->get($field->input_type);
		if(!$module instanceof InputfieldHasArrayValue) return $this->getSingleValue($field,array_pop($value));
		$return = new WireArray();
		foreach ($value as $val) $return->add($this->getSingleValue($field,$val));
		return $return;
    }

    public function sleepValue(Page $page, Field $field, $value) {
		if($value instanceof SelectExtOption) return ($value->value)?array($value->value):null;
		$return = array();
		if($value instanceof WireArray) {
	 		foreach ($value as $object) {
		    	if(!$object instanceof SelectExtOption) throw new WireException("Expecting an instance of SelectExtOption");
		    	if ($object->value === null) continue;
				$return[] = $object->value;
			}
		}
		return $return;
    }
	
	public function ___getConfigInputfields(Field $field) {

		$inputfields = parent::___getConfigInputfields($field);

		// choose inputfieldtype
		$f = $this->modules->get('InputfieldSelect');
		$f->label = _('Inputfieldtype');
		$f->attr('name', 'input_type');
		$f->attr('value', $field->input_type);
		$f->required = true;
		$f->description = $this->_('Select the type of Inputfield.');
		$f->notes = '* ' . $this->_('Types indicated with an asterisk are for multiple selection. Maybe 3rd party Inputfields will not work as expected. Please test carefully.');
		$f->addOption('InputfieldSelect', 'Select');
		foreach($this->modules->get("InputfieldPage")->data['inputfieldClasses'] as $class) {
			$module = $this->modules->get($class);
			if(is_subclass_of($module, 'InputfieldSelect') && method_exists($class,'___render')) {
				$label = str_replace("Inputfield", '', $class);
				if($module instanceof InputfieldHasArrayValue) $label .= "*";
				$f->addOption($class, $label);
			}
		}
		$inputfields->append($f);

		// create options
		$fieldset = $this->modules->get("InputfieldFieldset");
		$fieldset->label = _('Create options from any database table');
		$fieldset->notes = _("Save after selecting 'Source Table' to populate the appropriate select for 'Option Label' and 'Option Value'. Make a selection and save again.");
		$inputfields->add($fieldset);

		// source table
		$f = $this->modules->get("InputfieldSelect");
		$f->label = _("Source Table");
		$f->attr('name', 'option_table');
		$f->required = true;
		$f->attr('value', $field->option_table);
		if (!$field->option_table) $f->addOption(null, 'no table selected!',array('selected'=>'selected'));
		if ($this->getExtOptions($field->option_table) === null && !count($_POST)) $f->error('Table doesn\'t contain any data!');
		foreach ($this->db->getTables() as $table) $f->addOption($table, $table);
		$f->description = _("Choose a table in your database.");
		$f->columnWidth = 33;
		$fieldset->append($f);

		$columns = $this->getDatabaseColumns($field->option_table);
		// option value column
		$f = $this->modules->get("InputfieldSelect");
		$f->label = _("Option Value");
		$f->attr('name', 'option_value');
		$f->attr('value', $field->option_value);
		$f->description = _("Choose an integer type column.");
		if ($columns) foreach ($columns as $value) {
			if ($this->isIntColumn($field->option_table,$value)) $f->addOption($value, $value);
		}
		if ($field->option_table && !count($f->getOptions()) && !count($_POST)) $f->error("Only tables with columns of type 'integer' allowed!");
		if (!$field->option_value) $f->addOption(null, 'no column selected!',array('selected'=>'selected'));		
		$f->columnWidth = 34; 
		$fieldset->append($f);

		// option label column
		$f = $this->modules->get("InputfieldSelect");
		$f->label = _("Option Label");
		$f->attr('name', 'option_label');
		$f->attr('value', $field->option_label);
		$f->description = _("Choose from all columns.");
		if (!$field->option_label) $f->addOption(null, 'no column selected!',array('selected'=>'selected'));
		if ($columns) foreach ($columns as $label) $f->addOption($label, $label);
		$f->columnWidth = 33; 
		$fieldset->append($f);

		// option filter
		$fieldset = $this->modules->get("InputfieldFieldset");
		$fieldset->label = _('Filter');
		$fieldset->description = _("Configure to limit the option list.");
		$fc=($field->filter_column)?$field->filter_column:'[Column]';
		$fs=($field->filter_selector)?$field->filter_selector:'[Selector Operator]';
		$fv=($field->filter_value)?$field->filter_value:'[Value]';
		$fieldset->notes = _("SELECT * FROM $field->option_table WHERE $fc$fs'$fv'");
		$fieldset->collapsed = Inputfield::collapsedBlank;
		$fieldset->showIf = "option_value!=''";
		$inputfields->add($fieldset);

		// filter column
		$f = $this->modules->get("InputfieldSelect");
		$f->label = _("Column");
		$f->attr('name', 'filter_column');
		$f->attr('value', $field->filter_column);
		if ($columns) foreach ($columns as $filtercol) $f->addOption($filtercol, $filtercol);
		$f->columnWidth = 33; 
		$fieldset->append($f);

		// filter selector
		$f = $this->modules->get("InputfieldSelect");
		$f->label = _("Selector Operator");
		$f->attr('name', 'filter_selector');
		$f->attr('value', $field->filter_selector);
		$selectors = array('=', '<', '>', '>=', '<=', '<>', '!=', ' LIKE ',' NOT LIKE ');
		foreach ($selectors as $selector) $f->addOption($selector, $selector);
		$f->columnWidth = 34; 
		$fieldset->append($f);

		// filter value
		$f = $this->modules->get("InputfieldText");
		$f->label = _("Value");
		$f->attr('name', 'filter_value');
		$f->attr('value', $field->filter_value);
		$f->columnWidth = 33; 
		$fieldset->append($f);

		// option orderby
		$f = $this->modules->get("InputfieldSelect");
		$f->label = _("Order by");
		$f->description = _("Default: Order by label");
		$f->attr('name', 'option_order');
		$f->attr('value', $field->option_order);
		if ($columns) foreach ($columns as $ordercol) $f->addOption($ordercol, $ordercol);
		$f->collapsed = Inputfield::collapsedYes;
		$f->showIf = "option_value!=''";
		$inputfields->append($f);

		// option order asc/ desc
		$f = $this->modules->get("InputfieldRadios");
		$f->label = _("Order Direction");
		$f->attr('name', 'option_asc');
		($field->option_asc)?$f->attr('value', $field->option_asc):$f->attr('value', 0);
		$f->addOption(0,"Ascending");
		$f->addOption(1,"Descending");
		$f->collapsed = Inputfield::collapsedYes;
		$f->showIf = "option_value!=''";
		$inputfields->append($f);

		return $inputfields;
	}
}

/**
* Helper WireData Class to hold a SelectExtOption object
*
*/
class SelectExtOption extends WireData {

	public function __construct() {
		$this->set('value', null);
		$this->set('label', null);
		$this->set('row', array()); // TODO subclass with datatable column as properties. Problem: 'data' protected in WireData
	}

	public function set($key, $value) {
		if($key == 'value' || $key == 'label' || $key == 'row') {
			// validation of label ? 
			if($key == 'value' && !is_null($value) && !is_int($value)) throw new WireException("SelectExtOption object only accepts integer (int) as value property");
			if($key == 'row' && !is_array($value)) throw new WireException("SelectExtOption object only accepts arrays as row property");
		}
		return parent::set($key, $value);
	}

	public function get($key) {
		return parent::get($key);
	}
}
